[module]
module.name = "Numbers\Audiences\Audiences"
module.code = "AU"
module.title = "Audiences"
module.version = "1.0.0"

[dependencies]
dep.submodule.Numbers.Backend.Db.__any = 1
dep.submodule.Numbers.Backend.System.Modules = 1
dep.submodule.Numbers.Backend.System.WebSockets = 1
dep.submodule.Numbers.Tenants.Tenants = 1
dep.submodule.Numbers.Users.Organizations = 1
dep.submodule.Numbers.Users.Users = 1
dep.submodule.Numbers.Users.APIs = 1
;dep.submodule.Numbers.FlowTracker.FlowTracker = 1

; --- models (name and parent class) ---
dep.model.\Numbers\Audiences\Audiences\Model\Settings = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Groups = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Audiences = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Audience\Organizations = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Audience\Groups = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Contacts = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Contact\Audiences = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Contact\Groups = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Contact\Organizations = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Contact\PIIs = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Contact\Languages = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Contact\Skills = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Segments = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Segment\Groups = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Segment\Details = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Segment\Detail\ValuesIDs = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Senders = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Campaigns = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Campaign\Groups = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Campaign\Segments = "\Object\Table"
dep.model.\Numbers\Audiences\Audiences\Model\Campaign\Contacts = "\Object\Table"

; imports
dep.model.\Numbers\Audiences\Audiences\Data\Import = "\Object\Import"
dep.model.\Numbers\Audiences\Audiences\Data\System = "\Object\Import"
dep.model.\Numbers\Audiences\Audiences\Data\ShareableFields = "\Object\Import"
dep.model.\Numbers\Audiences\Audiences\Data\Tasks = "\Object\Import"

; loc
dep.loc.\Numbers\Audiences\Audiences\Localization\Messages = "Other"

; seeders
dep.seeder.\Numbers\Audiences\Audiences\Seeder\GroupsDevCleaner = "A/U Groups Dev Cleaner"
dep.seeder.\Numbers\Audiences\Audiences\Seeder\GroupsDevSeeder = "A/U Groups Dev Seeder"
dep.seeder.\Numbers\Audiences\Audiences\Seeder\AudiencesDevCleaner = "A/U Audiences Dev Cleaner"
dep.seeder.\Numbers\Audiences\Audiences\Seeder\AudiencesDevSeeder = "A/U Audiences Dev Seeder"
dep.seeder.\Numbers\Audiences\Audiences\Seeder\ContactsDevCleaner = "A/U Contacts Dev Cleaner"
dep.seeder.\Numbers\Audiences\Audiences\Seeder\ContactsDevSeeder = "A/U Contacts Dev Seeder"

[help]
; Audiences module for Numbers Framework
